-- 쇼핑몰 프로젝트 관련 테이블 --
-- 테이블 : 회원 정보, 상품 종류, 상품 정보, 상품 이미지 정보, 장바구니, 구매 정보
-- 회원 정보 테이블
CREATE TABLE SHOP_MEMBER (
    MEM_ID VARCHAR2(100) CONSTRAINT PK_SHOP_MEMBER PRIMARY KEY -- 아이디
    , MEM_PW VARCHAR2(100) NOT NULL -- 비밀번호
    , MEM_NAME VARCHAR2(100) NOT NULL -- 이름
    , MEM_PHONE VARCHAR2(100) NOT NULL -- 연락처(010-1111-1234)
    , MEM_EMAIL VARCHAR2(200) NOT NULL -- 이메일(abc@abc.net)
    , MEM_ADDRESS VARCHAR2(300) NOT NULL -- 주소
    , IS_ADMIN VARCHAR2(6) DEFAULT 'N' -- 운영자여부(Y,N)
    , JOIN_DATE DATE DEFAULT SYSDATE
);

COMMENT ON TABLE SHOP_MEMBER IS '쇼핑몰 회원정보 테이블';
COMMENT ON COLUMN SHOP_MEMBER.MEM_ID IS '회원 아이디';
COMMENT ON COLUMN SHOP_MEMBER.MEM_PW IS '회원 비밀번호';
COMMENT ON COLUMN SHOP_MEMBER.MEM_NAME IS '회원 이름';
COMMENT ON COLUMN SHOP_MEMBER.MEM_PHONE IS '회원 연락처';
COMMENT ON COLUMN SHOP_MEMBER.MEM_EMAIL IS '회원 이메일';
COMMENT ON COLUMN SHOP_MEMBER.MEM_ADDRESS IS '회원 주소';
COMMENT ON COLUMN SHOP_MEMBER.IS_ADMIN IS '운영자 여부';
COMMENT ON COLUMN SHOP_MEMBER.JOIN_DATE IS '회원가입 날짜';

-- 상품 종류 테이블
CREATE TABLE ITEM_CATEGORY (
    CATE_CODE VARCHAR2(50) CONSTRAINT PK_ITEM_CATEGORY PRIMARY KEY -- 카테고리 번호(CATE_001)
    , CATE_NAME VARCHAR2(100) NOT NULL -- 카테고리 이름
);

COMMENT ON TABLE ITEM_CATEGORY IS '상품 종류 테이블';
COMMENT ON COLUMN ITEM_CATEGORY.CATE_CODE IS '카테고리 번호';
COMMENT ON COLUMN ITEM_CATEGORY.CATE_NAME IS '카테고리 이름';

-- 상품 정보 테이블
CREATE TABLE SHOP_ITEM (
    ITEM_CODE VARCHAR2(100) CONSTRAINT PK_SHOP_ITEM PRIMARY KEY -- 상품 번호(ITEM_001)
    , ITEM_NAME VARCHAR2(100) NOT NULL UNIQUE -- 상품 이름
    , ITEM_PRICE NUMBER NOT NULL -- 상품 가격
    , ITEM_DETAIL VARCHAR2(1000) -- 상품 설명
    , ITEM_STOCK NUMBER DEFAULT 10 -- 상품 재고
);

COMMENT ON TABLE SHOP_ITEM IS '상품 정보 테이블';
COMMENT ON COLUMN SHOP_ITEM.ITEM_CODE IS '상품 번호';
COMMENT ON COLUMN SHOP_ITEM.ITEM_NAME IS '상품 이름';
COMMENT ON COLUMN SHOP_ITEM.ITEM_PRICE IS '상품 가격';
COMMENT ON COLUMN SHOP_ITEM.ITEM_DETAIL IS '상품 설명';
COMMENT ON COLUMN SHOP_ITEM.ITEM_STOCK IS '상품 재고';